apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: "{{ ALERTMANAGER_SLACK_API_URL }}"
      smtp_smarthost: "{{ ALERTMANAGER_SMTP_SMARTHOST }}"
      smtp_from: "{{ ALERTMANAGER_SMTP_FROM }}"
      smtp_auth_username: "{{ ALERTMANAGER_SMTP_USER }}"
      smtp_auth_password: "{{ ALERTMANAGER_SMTP_PASSWORD }}"
    templates:
    - "/etc/alertmanager/template/*.tmpl"
    route:
      group_by: ["alertname", "cluster", "service"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: default-receiver
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: "null"
    inhibit_rules:
    - source_match:
        severity: "critical"
      target_match:
        severity: "warning"
      equal: ["alertname", "cluster", "service"]
    receivers:
    - name: default-receiver
      slack_configs:
      - channel: "{{ ALERTMANAGER_SLACK_CHANNEL }}"
        send_resolved: true
      email_configs:
      - to: "{{ ALERTMANAGER_ALERT_EMAIL }}"
        send_resolved: true
    - name: "null"
