apiVersion: v1
kind: Namespace
metadata:
  name: "{{ LOGGING_NAMESPACE }}"
  labels:
    app.kubernetes.io/name: fluent-bit
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
